# Generated by Django 3.2.4 on 2021-06-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('catagory', models.IntegerField(choices=[(0, 'Sofa'), (1, 'Chair'), (2, 'Table'), (3, 'Dining Table'), (4, 'Bed'), (5, 'Not specified')])),
                ('description', models.CharField(default='', max_length=250)),
                ('Original_price', models.IntegerField(default=0)),
                ('Discounted_price', models.IntegerField(default=0)),
            ],
        ),
    ]
